name: CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Build
        run: go build .

  lint-install-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run ShellCheck
        run: shellcheck ./install.sh

